# Generated by Django 5.2.4 on 2025-07-29 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slowko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angielski', models.CharField(max_length=100)),
                ('polski', models.CharField(max_length=100)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slowka', to='nauka.lista')),
            ],
        ),
    ]
